### ISSUE TITLE
Make error handling consistent across all packages

### ISSUE THREAD

**Issue by xmudrii** [kubernetes-sigs/cluster-api-provider-digitalocean#104]
**User story**

In #87 the error handling got improved for some packages. We should check other packages and make sure the error checking and handling is consistent across all packages.

We could research is it possible to overall improve logging and error handling. For ideas, we can see how other providers handle this.

**Acceptance criteria**

- [ ] Make error handling consistent across all packages
- [ ] Potentially, find a better way for error handling and logging

**Comment by nikhita** [comment]
Created https://github.com/kubermatic/cluster-api-provider-digitalocean/pull/109 to make the error handling consistent across the project.

Re logging: we use glog currently but there has been discussion about how glog might not be a good choice for logging - https://github.com/kubernetes/kubernetes/issues/61006.

Fwiw, with respects to the project moving upstream, Kubernetes itself uses glog right now and it doesn't look like it is going to move away from it soon.

**Comment by xmudrii** [comment]
@solidnerd Moving to `klog` would be very useful and my plan is to do it once #126 is merged.

If you'd like to take on it as well, let us know. I would just recommend waiting for #126 or working based on that branch, as there are some packages that are added and removed.

**Comment by solidnerd** [comment]
@xmudrii I can take it and work from #126 as base. After the merge we can rebase it.

**Comment by xmudrii** [comment]
@solidnerd Sounds good, thanks! :)

**Comment by solidnerd** [comment]
@xmudrii what is missing here to bring this issue over the line ?

**Comment by xmudrii** [comment]
@solidnerd I think it's okay to close this issue. Thanks for the help!

/close
