### ISSUE TITLE
How to bump cluster-api version ?

### ISSUE THREAD

**Issue by solidnerd** [kubernetes-sigs/cluster-api-provider-digitalocean#130]
Hey,
I would also find it really interesting to update the cluster api in this project. To use kind as bootstraper. Currently I have no really clue how to update the cluster library and test this.

Thanks for your feedback on this

**Comment by xmudrii** [comment]
/assign
/priority important-soon

This should be fixed as soon as possible to make the provider actually usable. I'll try to take care of it soon.

**Comment by andrewrynhard** [comment]
Any plans on updating to newer CAPI soon? How can we help?

**Comment by xmudrii** [comment]
We’ll use the latest Cluster-API for v1alpha2, but we will not update the v1alpha1 branch to the latest v1alpha1 Cluster-API. That would take a lot of time and that branch will be archived soon anyways.

/close
