### ISSUE TITLE
Support cluster-api v1alpha2

### ISSUE THREAD

**Issue by prksu** [kubernetes-sigs/cluster-api-provider-digitalocean#139]
CAPI already has `v1alpha2` API type. Seems this Cluster API Provider doesn't have it yet.
I interested in update the repository to be supported. I already started doing this and will open a PR when ready. The progress can be tracked [here](https://github.com/prksu/cluster-api-provider-digitalocean/tree/support-capi-v1alpha2)

/cc @cluster-api-do-maintainers

**Comment by prksu** [comment]
/assign

friendly ping @xmudrii

**Comment by xmudrii** [comment]
Hello @prksu,

That sounds great! I had no time to work on updating this provider to `v1alpha2`, but if you are interested, that would be great! I just recommend syncing with @joonas, as he was also interested in doing so, but I'm not sure how is he progressing.

/cc @joonas

**Comment by prksu** [comment]
Hi @xmudrii thanks for the fast response 😀
And sounds good if there are other people who are also interested.

**Comment by andrewrynhard** [comment]
@prksu, @rsmitty and I might be able to help too.

**Comment by prksu** [comment]
hi @andrewrynhard glad to know you can help too

i just opened a PR for this work #140
And still need documentation and testing

After that, maybe we can bump to `v1alpha3`soon
