### ISSUE TITLE
Update e2e test using Cluster API test framework

### ISSUE THREAD

**Issue by prksu** [kubernetes-sigs/cluster-api-provider-digitalocean#175]
/kind feature

The current cluster api provider digitalocean e2e test is based on capi `v1alpha2` types. Some `v1alpha3` types like `KubeadmControlPlane` have not covered yet. Also Cluster API provides a test framework contains a set of helpers method to running an e2e test and based on this doc ([Developing E2E tests](https://cluster-api.sigs.k8s.io/developer/e2e.html)) it seems become standard in developing e2e test for cluster api providers.

**Comment by cpanato** [comment]
@prksu this is something that you are working on? otherwise, I will take it if you don't mind
