### ISSUE TITLE
Release for v1alpha3

### ISSUE THREAD

**Issue by andrewrynhard** [kubernetes-sigs/cluster-api-provider-digitalocean#178]
We would like to try this provider out, but need v1alpha3. Are there any plans to cut a new release any time soon?

**Comment by xmudrii** [comment]
@andrewrynhard There are currently two tasks blocking the release (#175 and #176). Once those tasks are complete, we'll be cutting a new release. Right now, we're not sure how long that will take.

**Comment by glennslaven** [comment]
Hi, I saw that those two issues are merged, does that mean a v1alpha3 version will be released soon?

**Comment by xmudrii** [comment]
We’ve released a Release Candidate which includes support for v1alpha3 earlier today. We’ll release an official release in the upcoming days.

**Comment by cpanato** [comment]
release is out: https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/releases/tag/v0.4.0
/close
