### ISSUE TITLE
Error when running example generate script.

### ISSUE THREAD

**Issue by glennslaven** [kubernetes-sigs/cluster-api-provider-digitalocean#194]
Provider version: v0.4.0

Command run : 
`/cluster-api-provider-digitalocean/examples/generate.sh`

Output:
```
Generated ./cluster-api-provider-digitalocean/examples/_out/cluster.yaml
Generated ./cluster-api-provider-digitalocean/examples/_out/controlplane.yaml
Generated ./cluster-api-provider-digitalocean/examples/_out/machinedeployment.yaml
Generated ./cluster-api-provider-digitalocean/examples/core-components/cluster-api-components.yaml
Generated ./cluster-api-provider-digitalocean/examples/core-components/bootstrap-components.yaml
Generated ./cluster-api-provider-digitalocean/examples/_out/core-components.yaml
Generated ./cluster-api-provider-digitalocean/examples/provider-components/provider-components-digitalocean.yaml
Error: no matches for OriginalId apps_v1_Deployment|capdo-system|capdo-controller-manager; no matches for CurrentId apps_v1_Deployment|capdo-system|capdo-controller-manager; failed to find unique target for patch apps_v1_Deployment|capdo-controller-manager
Generated ./cluster-api-provider-digitalocean/examples/_out/provider-components.yaml
WARNING: ./cluster-api-provider-digitalocean/examples/_out/provider-components.yaml includes DO credentials
```

The error:
 `Error: no matches for OriginalId apps_v1_Deployment|capdo-system|capdo-controller-manager; no matches for CurrentId apps_v1_Deployment|capdo-system|capdo-controller-manager; failed to find unique target for patch apps_v1_Deployment|capdo-controller-manager`

**Comment by prksu** [comment]
Hi @glennslaven , We don't use the example generator anymore, you can use `clusterctl` instead. But there is no documentation for `capdo` for now. Of course, we will add the documentation soon.

**Comment by timoreimann** [comment]
I wasn't fully aware that the examples aren't used anymore when I submitted #207 to fix the problem.

I suppose we can close this issue now though nevertheless.

**Comment by prksu** [comment]
provider version: v0.4.0+ could use `clusterctl`

/close
