### ISSUE TITLE
Support External Etcd storage

### ISSUE THREAD

**Issue by cpanato** [kubernetes-sigs/cluster-api-provider-digitalocean#197]
Add support to add an external storage for etcd

/kind feature
/help

**Comment by prksu** [comment]
This feature is possible by making use of the [CABPK: Support disk_setup and mounts in cloud-init](https://github.com/kubernetes-sigs/cluster-api/pull/3066) feature. The known provider uses this feature is [CAPZ](https://capz.sigs.k8s.io/topics/data-disks.html)

**Comment by gottwald** [comment]
I'll take a look into this one
