### ISSUE TITLE
cannot run two clusters in different namespaces but equal names due to existing LB configuration

### ISSUE THREAD

**Issue by timoreimann** [kubernetes-sigs/cluster-api-provider-digitalocean#217]
The LB created for each cluster uses [a configuration](https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/blob/61e0d233543fe6e7cd077d358aa5340888ae3a2c/cloud/services/networking/loadbalancers.go#L43-L75) that chooses the LB name based on the cluster name and target role (i.e., master/worker). This is problematic when using two clusters in different namespaces with the same name because the second LB being created will fail due to name uniqueness constraints that the DO LB API imposes:

```
E1207 14:00:12.321286       1 controller.go:248] controller-runtime/controller "msg"="Reconciler error" "error"="failed to create load balancers for DOCluster namespace2/worker-cluster: POST https://api.digitalocean.com/v2/load_balancers: 422 (request \"656cf44f-f12c-45e9-9d52-1fdc1c8f095a\") name is not unique" "controller"="docluster" "name"="worker-cluster" "namespace"="namespace2"
```

Moreover, the tag configured on each LB that is to identify the matching droplets follows the same naming schema. So even if unique LB names are chosen, additional effort must be taken to ensure that LBs only target their respective cluster nodes.

I think that a unique, cluster-specific, auto-generated identifier should be included in the LB name, droplet tags, and LB droplet target tag to guarantee proper separation. Upstream CCM picks the Service UID as the default name, which could be leveraged for the LB as well.
Including the namespace in the LB name/droplet target tag would still be helpful to ease identifying LBs in the cloud control panel UI / API.

Finally, some side observation: the LB create errors does not seem to propagate as an event anywhere, which makes it harder than necessary to see the problem. Perhaps we can improve in this regard as well while we're at things.

**Comment by prksu** [comment]
@timoreimann , I'm thinking about adding cluster UID in LB name and droplet target tag. I'll create the PR soon
