### ISSUE TITLE
Add Timo Reimann to the KubernetesE2ETesting DO account

### ISSUE THREAD

**Issue by MorrisLaw** [kubernetes-sigs/cluster-api-provider-digitalocean#237]
### Users affected
@timoreimann 

### Describe the issue
Timo Reimann has been added as a co-maintainer to this repo (kubernetes-sigs/cluster-api-provider-digitalocean). He needs access to the CNCF sponsored DigitalOcean account, `KubernetesE2ETesting`. Can we add him via his email: ttr314@googlemail.com

**Comment by idvoretskyi** [comment]
@MorrisLaw access granted, enjoy!

**Comment by MorrisLaw** [comment]
Thank you @idvoretskyi!

**Comment by MorrisLaw** [comment]
Confirmed w/ @timoreimann that he has access now.

**Comment by timoreimann** [comment]
Thanks @MorrisLaw for taking care of things!
