### ISSUE TITLE
Allow HA cluster setups

### ISSUE THREAD

**Issue by xmudrii** [kubernetes-sigs/cluster-api-provider-digitalocean#45]
`cluster-api-provider-digitalocean` can only bootstrap a single-master cluster now.

This is currently an upstream issue, and update is up to follow.

**Comment by alvaroaleman** [comment]
@xmudrii Is there an upstream issue for this? I tried to find one but didn't.

**Comment by xmudrii** [comment]
@alvaroaleman Not that I'm aware of. Possibly could be created in cluster-api repo.

**Comment by alvaroaleman** [comment]
Does it belong there? Because at the end of the day the scripts that are responsible for creating a control plane (be it HA or not) live inside the providers or am I missing something here?

**Comment by xmudrii** [comment]
To some degree. It would nice to make sure the proposed solution is okay with the Cluster-API team. Also, some changes to API could be required to ensure coordination between masters is possible.

I still have not researched a lot about this issues but I hope to get on it soon.

It may be even more relevant to cluster-api if we decide to upstream provisioning logic.

**Comment by xmudrii** [comment]
This potentially could be handled at the provider level as well. It seems like there are some examples in the CAPI AWS provider.

/remove-lifecycle rotten
