### ISSUE TITLE
UMBRELLA: clusterctl doesn't work with Minikube > 0.28

### ISSUE THREAD

**Issue by alvaroaleman** [kubernetes-sigs/cluster-api-provider-digitalocean#78]
Hello,

Trying out the getting started part of the README, `clusterctl` got stuck on the `Creating master in namespace "kube-system"` step, the underlying problem was this:

```
$ k logs -n kube-system clusterapi-controllers-59c87fb589-x4jrf digitalocean-machine-controller -f
I0930 09:39:50.136817       1 leaderelection.go:174] attempting to acquire leader lease...
E0930 09:39:50.151867       1 leaderelection.go:224] error retrieving resource lock kube-system/digitalocean-machine-controller: Get https://localhost:8443/api/v1/namespaces/kube-system/endpoints/digitalocean-machine-controller: dial tcp 127.0.0.1:8443: connect: connection refused
```

I worked around this by setting `hostNetwork: true` in `clusterapi-controllers` deployment, because otherwise `localhost` is the lo interface in the pods net namespace and not in the root net namespace where the minikube apiserver runs.

**Comment by xmudrii** [comment]
@alvaroaleman There is upstream issue for this problem. clusterctl doesn't work very well with Minikube > 0.28.

I created a PR #82 to add `hostNetwork: true` and to add a note in README that Minikube < 0.28 is recommended.

Relevant upstream issue: https://github.com/kubernetes-sigs/cluster-api/issues/475
