### ISSUE TITLE
Add support for DigitalOcean Custom Images

### ISSUE THREAD

**Issue by xmudrii** [kubernetes-sigs/cluster-api-provider-digitalocean#92]
**Introduction**

DigitalOcean now supports [Custom Images](https://blog.digitalocean.com/custom-images/), ensuring users can upload their own images in one of supported formats and use them to provision a Droplet.

**User story**

User builds an image with Kubernetes installed and pre-configured and use that image to bootstrap a Droplet. Provisioning script now only contains function for initializing a cluster or joining existing cluster.

This is especially important for users running in production, as:
- Users use better mechanism for building images, rather than using Bash scripts, that may be easier to maintain and version
- It is easier to test is image working as expected
- It is easier to share images between users and customers

**Prerequisites**

- [x] There is API support for Custom images ([API documentation](https://developers.digitalocean.com/documentation/v2/#images))
- [ ] `godo` supports working with Custom Images

**Acceptance criteria**

- [ ] Users can specify custom image to be used rather than only being able to use default images
- [ ] Documentation is updated to state how to use custom images

**Comment by prksu** [comment]
@xmudrii after this PR #140 we already support custom images and documented in [getting started](https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/blob/master/docs/getting-started.md#building-images)

maybe we can close this issue
